name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_NAME: demo_credit

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"$DB_HOST" -P"$DB_PORT" --silent; do
          sleep 1
        done

    - name: Install DB ORM
      run: npm install knex -g

    - name: Run migrations
      run: npm run migrate

    - name: Test prebuild
      run:  npm run build --if-present
    
    - name: Run tests
      run: npm test